port: 1999
bind: '*'

log-level: 'debug'

proxies:
  - name: 'proxy'
    type: 'http'
    host: 'localhost'
    port: 8080
    rules:
      - '"secret" in request.headers.keys'
      - 'ip.geoip.country == "IR"'

  - name: 'direct'
    type: 'direct'
    rules:
      - 'ip.geoip.country == "IR"'
