port: 1999
bind: '*'

log-level: 'debug'

proxies:
  - name: 'proxy'
    type: 'http'
    host: 'localhost'
    port: 8080

  - name: 'direct'
    type: 'direct'

rules:
  - rule: '"secret" in request.headers.keys'
    proxy: direct

  - rule: 'ip.geoip.country == "IR"'
    proxy: direct

  - rule: 'match'
    proxy: proxy
